### PR TITLE
Plaster a notice onto the site home page that the group is inactive due to the strike; also FAQ updates

### PR DESCRIPTION
**Pull request by gparyani**
All bots are currently inactive due to Charcoal and SOBotics participating in the content moderation strike. Also, per the linked post, forcing an edit is no longer possible as SE added a server-side check for pending suggested edits. Finally, make some other minor edits, such as required commas on "e.g.," and "i.e.,".

### CODE REVIEW

**Comment by gparyani** [comment]
I just added another commit to plaster a notice onto the home page of the strike.

**Review by makyen — CHANGES_REQUESTED** [review]
1. Please submit separate PRs for these changes. At a minimum, please make the changes for different things in separate commits.  
   Very specifically: Any changes regarding notifications about the strike or the status of another project should be in a commit that includes no changes which are expected to be live after the strike ends. At the end of the strike such changes will need to be reverted. It is *far* easier to do that by just reverting one or more commits, rather than having to manually re-edit.
2. If there should be a comma after "e.g." and "i.e." appears to be a US/UK English differentiation, and even some variation between "i.e." and "e.g.". Please see [answer to: 'Should I always use a comma after "e.g." or "i.e."?'](https://english.stackexchange.com/a/602614/93396) and the other answers to that question. We should pick one and stick with it. I haven't looked to see which is more commonly used in the site, but unless there's consensus for using one or the other, I'd stick with whatever it was which was more commonly used or used first.
3. While I don't disagree with removing the comment about forcing an edit, it actually is still possible to force an edit, but doing so is a bit more involved and most easily done with a userscript.
4. While I don't object to a notification about the strike being on the home page, I'd prefer to keep the "Welcome" header and have a separate notification under that header, probably as an H2.
5. Why was the "(currently inactive)" text removed from some bots which are still currently inactive?

**Comment by gparyani** [comment]
@makyen 

1. Sorry, I forgot that my edits are being saved as commits on Git - kind of hard to think of that when you're not working on code.
2. I was legitimately unaware that it was a regional difference. I was going off of grammar recommendations issued by the Edge browser, which told me that it is "wrong" to have no comma and that it was required.
3. I was going off of the post which was linked in that paragraph, which in its latest revision at the time of the PR said that it was no longer possible and did not mention a user script workaround.
4. Sorry about that. I was going off of Charcoal's website which had an h1 heading for the strike.
5. I felt that the text was redundant since I added in a new paragraph which said that all bots are currently inactive due to the strike. Are you talking about bots that are inactive for reasons other than the strike (i.e., will not be returning to activity once the strike is over)?

At this point, especially given issue 1, I think it's best if this PR were rejected and I open a fresh one to fix these issues. As such, I'm closing this.

**Comment by makyen** [comment]
1. No problem. It's just a lot easier to have separate commits when there are different types of changes, particularly when we _expect_ that we will eventually revert some of the changes (i.e., when the strike ends).
2. Yeah, I wasn't aware it was a regional difference until the dispute about if a comma should be after "e.g." in the title of the genGI is banned post on MSO resulted in someone linking to the Q&A I linked.
3. I need to update that post based on newer information. I've been intending to write such a userscript, but just haven't gotten around to it. Although, I have at least tested to prove that it's possble.
4. Yeah, the review on that change wasn't very picky, potentially because it was assumed that the strike wouldn't take a long time.
5. The bots which are currently marked as inactive have been inactive for a long time. The listing for each of those bots haven't been removed for historical reasons (e.g., people looking at the chat transcript) and a hope that the bots might someday be revived. None of the ones currently marked as inactive are inactive due to the strike.

**Pull request closed without merging**
