### PR TITLE
Room Meeting: 2018-August

### PR DESCRIPTION
**Pull request by makyen**
This is a first pass at summarizing the 2018-August room meeting. I've probably gone a bit overboard in providing context and interpreting what was said. I may have permitted my own biases to intrude when interpreting the results, so please double-check that what I've written matches your understanding.

Comments and corrections are desired.

I have significant concerns regarding Topic# 2 (discussion about the rule to not request on asked, answered, edits). 
* Primarily, it's not clear to me if the 4 enumerated rules were intended to completely replace the rule that was being discussed.
  If they are to completely replace the rule that was the primary topic, then there are multiple issues. Among those issues are:
  * The 4 enumerated points don't consider request types other than `cv-pls` and `reopen-pls`.
  * Posting a `del-pls` for other people's answers on a question you've answered is now permitted.
  * Posting `approve-pls` on your own edits is now permitted. There was quite a bit of opposition to this in the [November 2017 meeting](https://chat.stackoverflow.com/rooms/108179/conversation/2017-november-topic-6).
* Were they also intended to replace portions, or all, of [FAQ #11](https://socvr.org/faq#GEfM-cv-pls-not-a-habit)? The inclusion of item 2 implies that they are.

I'm fine with doing an "intelligent" merge into the FAQ (i.e. minimal disruption), but I'm not clear on what everyone, at least the other ROs, are expecting.

### CODE REVIEW

**Comment by gunr2171** [comment]
LGTM, besides the confusion in topic 2.

**Comment by rschrieken** [comment]
We can only partial implement 2 as we missed the impact, conflict and incompleteness of the proposal. So I think we should change what we can and leave the remainder for the next roommeeting

**Review by rschrieken — COMMENTED** [review]
I'm fine with this. Lets gunr do the approve

**Comment by makyen** [comment]
Give me a sec, Looks like the preview program I used didn't show some of the indenting correctly.

**Review by gunr2171 — COMMENTED** [review]
I'd suggest moving 27 (limit cv-requests) to the "Be responsible with moderation requests" section (maybe right after 11?).

**Review by gunr2171 — APPROVED** [review]
otherwise, good job

**Comment by makyen** [comment]
Thanks.

Yeah, it's not in that section primarily because I was hesitating to change the numbering, particularly because we're changing FAQ#15 and most of the discussions refer to it by number. However, I agree that 27 should go in that section, and that after FAQ#11 is the most appropriate location.

I'll move it and deal with the number changes. At the moment, I'm looking at swapping the order of the current FAQ#14 and FAQ#15. This will leave FAQ#15 with the same number, which should lessen confusion of people tracking things from the room meeting.

**Pull request merged**
